// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_0LSYNtuTFrcwPN0zpPphgauopoZ97Fk',
    appId: '1:1063798082411:web:c7324b490701cc2352da2e',
    messagingSenderId: '1063798082411',
    projectId: 'memperio-52d1f',
    authDomain: 'memperio-52d1f.firebaseapp.com',
    storageBucket: 'memperio-52d1f.appspot.com',
    measurementId: 'G-G0STVM3JVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0YDGN277vB-jEgitx0cS4uKc4hJ-oQ1I',
    appId: '1:1063798082411:android:0f0e077f8530939352da2e',
    messagingSenderId: '1063798082411',
    projectId: 'memperio-52d1f',
    storageBucket: 'memperio-52d1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13xg2W7A-PUwVfsr1vlJzytr3o8DMF4E',
    appId: '1:1063798082411:ios:900b09fee6447d2052da2e',
    messagingSenderId: '1063798082411',
    projectId: 'memperio-52d1f',
    storageBucket: 'memperio-52d1f.appspot.com',
    iosBundleId: 'com.example.memperio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD13xg2W7A-PUwVfsr1vlJzytr3o8DMF4E',
    appId: '1:1063798082411:ios:0dbb60f9463528ea52da2e',
    messagingSenderId: '1063798082411',
    projectId: 'memperio-52d1f',
    storageBucket: 'memperio-52d1f.appspot.com',
    iosBundleId: 'com.example.memperio.RunnerTests',
  );
}
